### ISSUE TITLE
1.1.0版本，只要类的字段上打了DataFactory注解，就会报空指向

### ISSUE THREAD

**Issue by zerolijintao** [houbb/data-factory#5]
Exception in thread "main" java.lang.NullPointerException
	at com.github.houbb.data.factory.core.api.data.annotation.DefaultDataFactoryAnnotationData.buildDataValue(DefaultDataFactoryAnnotationData.java:27)
	at com.github.houbb.data.factory.core.api.data.annotation.DefaultDataFactoryAnnotationData.buildDataValue(DefaultDataFactoryAnnotationData.java:21)
	at com.github.houbb.data.factory.core.api.data.annotation.AbstractAnnotationData.build(AbstractAnnotationData.java:54)

**Comment by zerolijintao** [comment]
作者可以跑DataUtilAnnotationNumberTest这个测试类重现上面的问题

**Comment by houbb** [comment]
感谢提醒，V1.2.0 已修复。
